// Destination themes: a themed paper, local-language ephemera, sample notes and pressed flowers.
// `comp` picks one of the collage compositions in layouts.js (A, B or C).

export const DESTINATIONS = [
  {
    id: 'greece', name: 'Greece', comp: 'A',
    title: 'Greece', titleFont: 'Great Vibes', subtitle: 'Ελλάδα · summer ♡',
    paper: 'aegean', pages: ['cream', 'vintage'], tape: '#a9c6d8', ink: '#1f3a7a',
    stamp: { text: 'ΕΛΛΑΣ · HELLAS', text2: '€0.95', color: '#bcd3e8', motif: 'olive' },
    postmark: { text: 'ΑΘΗΝΑ · ATHINA', text2: '06 · 2026', color: '#1f3a7a' },
    ticket: { text: 'ACROPOLIS ΑΚΡΟΠΟΛΗ', text2: 'ΕΙΣΙΤΗΡΙΟ · ADMISSION', color: '#bcd3e8' },
    label: { text: 'SANTORINI · ΣΑΝΤΟΡΙΝΗ', text2: 'Οία · Oia', color: '#f5f2ea' },
    notes: ['blue domes &\nwhite walls ♡', 'sunsets in Oia\nevery single night', 'salt in our hair,\nfeta on everything'],
    captions: ['the Acropolis ♡', 'Oia at golden hour'],
    flowers: ['bougainvillea-pink', 'olive', 'jasmine'],
  },
  {
    id: 'italy', name: 'Italy', comp: 'B',
    title: 'Italia', titleFont: 'Pinyon Script', subtitle: 'la dolce vita ♡',
    paper: 'lemons', pages: ['cream', 'vintage'], tape: '#f1d58a', ink: '#2f5d3a',
    stamp: { text: 'ITALIA', text2: '€1,30', color: '#f1d58a', motif: 'lemon' },
    postmark: { text: 'ROMA', text2: '07 · 2026', color: '#2b2118' },
    ticket: { text: 'COLOSSEO ROMA', text2: 'BIGLIETTO · INTERO', color: '#e8d9b8' },
    label: { text: 'TRATTORIA DA NONNA', text2: 'dal 1962', color: '#efe3c6' },
    notes: ['gelato twice a day,\nno regrets ♡', 'Amalfi coast —\nlemons everywhere', 'ciao bella!'],
    captions: ['Roma ♡', 'Positano'],
    flowers: ['poppy', 'olive', 'rose'],
  },
  {
    id: 'switzerland', name: 'Switzerland', comp: 'C',
    title: 'Switzerland', titleFont: 'Great Vibes', subtitle: 'Schweiz · Suisse · Svizzera',
    paper: 'swiss', pages: ['cream', 'vintage'], tape: '#e8b4a6', ink: '#9e2a2b',
    stamp: { text: 'HELVETIA', text2: 'CHF 1.10', color: '#e8b4a6', motif: 'daisy' },
    postmark: { text: 'ZERMATT', text2: '08 · 2026', color: '#2b2118' },
    ticket: { text: 'GORNERGRAT BAHN', text2: 'FAHRKARTE · 2. KLASSE', color: '#e8b4a6' },
    label: { text: 'SCHWEIZER SCHOKOLADE', text2: 'feinste Milch', color: '#efe3c6' },
    notes: ['the Matterhorn took\nour breath away ♡', 'fondue &\nhot chocolate', 'mountain air'],
    captions: ['Zermatt ♡', 'Lake Lucerne'],
    flowers: ['gypsophila', 'cornflower', 'fern'],
  },
  {
    id: 'budapest', name: 'Budapest', comp: 'B',
    title: 'Budapest', titleFont: 'Pinyon Script', subtitle: 'Magyarország ♡',
    paper: 'kalocsa', pages: ['aged', 'vintage'], tape: '#c9d6b2', ink: '#2f5d3a',
    stamp: { text: 'MAGYARORSZÁG', text2: '450 Ft', color: '#c9d6b2', motif: 'poppy' },
    postmark: { text: 'BUDAPEST', text2: '05 · 2026', color: '#2b2118' },
    ticket: { text: 'SZÉCHENYI FÜRDŐ', text2: 'BELÉPŐJEGY · ENTRY', color: '#c9d6b2' },
    label: { text: 'KÖZPONTI VÁSÁRCSARNOK', text2: 'Nº 1897', color: '#efe3c6' },
    notes: ['thermal baths\nunder the stars ♡', 'kürtőskalács\n(chimney cake!)', 'the Danube at night'],
    captions: ['Parliament ♡', 'Széchenyi baths'],
    flowers: ['peony', 'poppy', 'lilac'],
  },
  {
    id: 'poland', name: 'Poland', comp: 'C',
    title: 'Polska', titleFont: 'Great Vibes', subtitle: 'Kraków · Warszawa ♡',
    paper: 'wycinanki', pages: ['cream', 'vintage'], tape: '#e8b4a6', ink: '#9e2a2b',
    stamp: { text: 'POLSKA', text2: '3,60 zł', color: '#e8b4a6', motif: 'poppy' },
    postmark: { text: 'KRAKÓW', text2: '09 · 2026', color: '#2b2118' },
    ticket: { text: 'KOPALNIA SOLI WIELICZKA', text2: 'BILET WSTĘPU', color: '#f1d58a' },
    label: { text: 'PIEROGARNIA', text2: 'u Babci', color: '#efe3c6' },
    notes: ['pierogi for\nevery meal ♡', 'the Old Town\nsquare at dusk', 'na zdrowie!'],
    captions: ['Rynek Główny ♡', 'Wawel'],
    flowers: ['cornflower', 'poppy', 'buttercup'],
  },
  {
    id: 'prague', name: 'Prague', comp: 'A',
    title: 'Praha', titleFont: 'Pinyon Script', subtitle: 'Prague · Česko ♡',
    paper: 'nouveau', pages: ['aged', 'vintage'], tape: '#d9c2e0', ink: '#6b3f6b',
    stamp: { text: 'ČESKO', text2: '26 Kč', color: '#d9c2e0', motif: 'blossom' },
    postmark: { text: 'PRAHA', text2: '04 · 2026', color: '#2b2118' },
    ticket: { text: 'PRAŽSKÝ HRAD', text2: 'VSTUPENKA · TICKET', color: '#d9c2e0' },
    label: { text: 'STAROMĚSTSKÝ ORLOJ', text2: 'od roku 1410', color: '#efe3c6' },
    notes: ['fairytale\nrooftops ♡', 'Charles Bridge\nat sunrise', 'trdelník &\nsvařák'],
    captions: ['the astronomical clock', 'Old Town ♡'],
    flowers: ['lilac', 'wisteria', 'peony'],
  },
  {
    id: 'croatia', name: 'Croatia', comp: 'A',
    title: 'Hrvatska', titleFont: 'Great Vibes', subtitle: 'Croatia · Dubrovnik ♡',
    paper: 'sahovnica', pages: ['vintage', 'map'], tape: '#a9c6d8', ink: '#1f3a5f',
    stamp: { text: 'HRVATSKA', text2: '€1,10', color: '#a9c6d8', motif: 'lavender' },
    postmark: { text: 'DUBROVNIK', text2: '07 · 2026', color: '#1f3a5f' },
    ticket: { text: 'NP PLITVIČKA JEZERA', text2: 'ULAZNICA · ENTRANCE', color: '#a9c6d8' },
    label: { text: 'KONOBA MARE', text2: 'riba · vino', color: '#efe3c6' },
    notes: ['the clearest\nwater ever ♡', 'island hopping\nall week', 'walking the\nwalls of Dubrovnik'],
    captions: ['Plitvice lakes', 'Old Town ♡'],
    flowers: ['lavender', 'olive', 'rosemary'],
  },
  {
    id: 'france', name: 'France', comp: 'B',
    title: 'France', titleFont: 'Pinyon Script', subtitle: 'Paris · Provence ♡',
    paper: 'breton', pages: ['cream', 'vintage'], tape: '#bcd3e8', ink: '#1f2f55',
    stamp: { text: 'RÉPUBLIQUE FRANÇAISE', text2: '€1,39', color: '#bcd3e8', motif: 'lavender' },
    postmark: { text: 'PARIS', text2: '06 · 2026', color: '#1f2f55' },
    ticket: { text: 'MUSÉE DU LOUVRE', text2: 'BILLET · ENTRÉE', color: '#e8d9b8' },
    label: { text: 'BOULANGERIE PÂTISSERIE', text2: 'depuis 1920', color: '#efe3c6' },
    notes: ['croissants on\nthe balcony ♡', 'lavender fields\nin Provence', 'oh là là!'],
    captions: ['la tour Eiffel ♡', 'Provence'],
    flowers: ['lavender', 'rose', 'poppy'],
  },
  {
    id: 'portugal', name: 'Portugal', comp: 'A',
    title: 'Portugal', titleFont: 'Great Vibes', subtitle: 'Lisboa · Porto ♡',
    paper: 'sardines', pages: ['aged', 'vintage'], tape: '#f1d58a', ink: '#1f3a5f',
    stamp: { text: 'PORTUGAL', text2: '€0,95', color: '#f1d58a', motif: 'orange' },
    postmark: { text: 'LISBOA', text2: '06 · 2026', color: '#1f3a5f' },
    ticket: { text: 'ELÉCTRICO 28', text2: 'BILHETE · CARRIS', color: '#f1d58a' },
    label: { text: 'PASTÉIS DE BELÉM', text2: 'desde 1837', color: '#efe3c6' },
    notes: ['pastéis de nata\nfor breakfast ♡', 'tram 28 up\nevery hill', 'azulejos\neverywhere'],
    captions: ['Alfama ♡', 'Porto sunsets'],
    flowers: ['bougainvillea-orange', 'jasmine', 'hibiscus'],
    extraPaper: 'azulejo',
  },
  {
    id: 'norway', name: 'Norway', comp: 'C',
    title: 'Norge', titleFont: 'Great Vibes', subtitle: 'Norway · fjords & northern lights',
    paper: 'nordic', pages: ['cream', 'vintage'], tape: '#a9c6d8', ink: '#1f3a5f',
    stamp: { text: 'NORGE', text2: '25 kr', color: '#a9c6d8', motif: 'fern' },
    postmark: { text: 'BERGEN', text2: '08 · 2026', color: '#1f3a5f' },
    ticket: { text: 'FLÅMSBANA', text2: 'BILLETT · TICKET', color: '#a9c6d8' },
    label: { text: 'FISKETORGET', text2: 'Bergen', color: '#efe3c6' },
    notes: ['the fjords are\nunreal ♡', 'we saw the\nnorthern lights!', 'cosy cabin nights'],
    captions: ['Geirangerfjord ♡', 'Bergen'],
    flowers: ['fern', 'eucalyptus', 'forget-me-not'],
  },
];

export const destination = (id) => DESTINATIONS.find((d) => d.id === id);
